---
- name: Alpine - Basic package upgrades
  ansible.builtin.include_tasks: alpine_upgrade.yaml
  when: ansible_facts['os_family'] == "Alpine"
  tags: always

- name: Debian - Basic package upgrades
  ansible.builtin.include_tasks: debian_upgrade.yaml
  when: ansible_facts['os_family'] == "Debian"
  tags: always

- name: Networking basic configuration
  ansible.builtin.include_tasks: networking.yaml
  when: (domain_name is defined)
  tags: always
