---
- name: Alpine - fail2ban configuration
  ansible.builtin.include_tasks: alpine_fail2ban.yaml
  when: ansible_facts['os_family'] == "Alpine"
  tags: always

- name: Debian - fail2ban configuration
  ansible.builtin.include_tasks: debian_fail2ban.yaml
  when: ansible_facts['os_family'] == "Debian"
  tags: always

# double up on the cloud-init sshd hardening
- name: Ensure sshd_config is configured with strict settings
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    owner: root
    group: root
    mode: '0600'
  loop:
    - { regexp: '^#?Port ', line: 'Port {{ ssh_port }}' }
    - { regexp: '^#?PermitRootLogin ', line: 'PermitRootLogin {{ ssh_permit_root_login }}' }
    - { regexp: '^#?PasswordAuthentication ', line: 'PasswordAuthentication {{ ssh_password_authentication }}' }
    - { regexp: '^#?ChallengeResponseAuthentication ', line: 'ChallengeResponseAuthentication {{ ssh_challenge_response_auth }}' }
    - { regexp: '^#?PubkeyAuthentication ', line: 'PubkeyAuthentication {{ ssh_pubkey_authentication }}' }
    - { regexp: '^#?PermitEmptyPasswords ', line: 'PermitEmptyPasswords {{ ssh_permit_empty_passwords }}' }
    - { regexp: '^#?MaxAuthTries ', line: 'MaxAuthTries {{ ssh_max_auth_tries }}' }
    - { regexp: '^#?LoginGraceTime ', line: 'LoginGraceTime {{ ssh_login_grace_time }}' }
    - { regexp: '^#?MaxSessions ', line: 'MaxSessions {{ ssh_max_sessions }}' }
    - { regexp: '^#?ClientAliveInterval ', line: 'ClientAliveInterval {{ ssh_client_alive_interval }}' }
    - { regexp: '^#?ClientAliveCountMax ', line: 'ClientAliveCountMax {{ ssh_client_alive_count_max }}' }
    - { regexp: '^#?Compression ', line: 'Compression {{ ssh_compression }}' }
    - { regexp: '^#?X11Forwarding ', line: 'X11Forwarding {{ ssh_x11_forwarding }}' }
  notify: restart sshd
  tags: always

# disable unused filesystems
- name: Ensure unused filesystems are disabled
  ansible.builtin.blockinfile:
    path: /etc/modprobe.d/disable-filesystems.conf
    state: present
    create: yes
    insertafter: EOF
    owner: root
    group: root
    mode: '0644'
    block: |
      install cramfs /bin/true
      install freevxfs /bin/true
      install jffs2 /bin/true
      install hfs /bin/true
      install hfsplus /bin/true
      install squashfs /bin/true
      install udf /bin/true
      install vfat /bin/true
  notify: restart system

# harden kernel parameters
- name: Harden kernel parameters
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/00-hardening.conf
    state: present
    reload: yes
  loop:
    - { name: 'net.ipv4.ip_forward', value: '0' }
    - { name: 'net.ipv4.conf.all.accept_source_route', value: '0' }
    - { name: 'net.ipv4.conf.all.accept_redirects', value: '0' }
    - { name: 'net.ipv4.conf.all.secure_redirects', value: '0' }
    - { name: 'net.ipv4.conf.all.log_martians', value: '1' }
    - { name: 'net.ipv4.conf.default.log_martians', value: '1' }
    - { name: 'net.ipv4.icmp_echo_ignore_broadcasts', value: '1' }
    - { name: 'net.ipv4.icmp_ignore_bogus_error_responses', value: '1' }
    - { name: 'net.ipv4.tcp_syncookies', value: '1' }
    - { name: 'net.ipv4.conf.all.send_redirects', value: '0' }
    - { name: 'net.ipv4.conf.default.send_redirects', value: '0' }
